#Servlst 容器
server:
  port: 9090
  servlet:
    context-path: /smbms_chd

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

     
      

  #数据源    
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
#前端 加8个时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd


mybatis:
  #config-location: mybatis-config.xml
  #扫描mapper文件
  mapper-locations: com/chd/smbms/dao/*/*mapper.xml
  #配置别名
  type-aliases-package: com.chd.smbms.pojo
  
